contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('', views.contact, name='contact'),
]

error/urls.py
from django.urls import path
from . import views


app_name = 'error'

urlpatterns = [
    path('', views.error, name='error'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from projects import views
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name ='home'),
    path('contact/', include('contact.urls')),
    path('error/', include('error.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='projects/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

contact/views.py
from django.shortcuts import render, get_object_or_404


def contact(request):
    return render(request, 'contact/contact.html', {'contact':contact})

projects/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'projects/home.html', {'projects':projects})

contact/templates/contact/contact.html
{% load static %}
<html lang='en' dir="ltr">
  <head>
     <meta charset="utf-8">
     <title>Ruby's Contact Page</title>
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'contact/style.css' %}">
  </head>
  <body>

     <div class="landing">
      <h1>Ruby's Contact Page</h1>
      <div class="content">
         <h2><span>Contact</span> me <span>to meet</span><br> for coffee.</h2>
         <p>Hi! If you like my work and are interested in working with me<br> please feel free to shoot me an e-mail for either freelance<br> work or a company position.
         </p>

         <a href = "mailto: rubyalesi@icloud.com">Send Email</a>
         <a role="button" href="{% url 'home' %}">Home</a>
     <img class="second" src="{% static 'contact/giphy.gif' %}">
   </div>
  </body>
 </html>

projects/templates/projects/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "projects/custom.css" %}">
<link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "projects/logo_icon2.jpg" %}">

  <title>Ruby Alesi</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">

        <img src="{% static "projects/logo_icon.jpg" %}" width="30" height="30" class="d-inline-block align-top" alt="Ruby's Logo">
        <span>Ruby Alesi</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <p class="nav-link" href="{% static "projects/Resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/codergirlruby10">GitHub</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

projects/templates/projects/home.html
{% extends 'projects/base.html' %}

{% block content %}


  {% load static %}

 <div class="row justify-content-center my-2">
   <div class="col-4">
     <img src="{% static 'projects/octocat.jpg' %}" class="img-fluid">
   </div>
</div>

<br>


<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Welcome to my Website!</h1>
  </div>
</div>


<h2 class="mt-6">Projects</h2>
<hr>
<div class="row">
 {% for project in projects %}
 <div class="col-lg-3 col-md-4">

   {% if project.url %}
   <a href="{{ project.url }}">
     <img src="{{ project.image.url }}" class="img-fluid mb-2">
   </a>
   {% else %}


   <img src="{{ project.image.url }}" class="img-fluid mb-2">
   {% endif %}
   <h2>{{ project.title }}</h2>
   <h5>{{ project.description }}</h5>

 </div>
 {% endfor %}
</div>

{% endblock %}